version: '3'

networks:
  mysqlnet:
    external: true

services:
  web:
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - ./:/app
    env_file:
      - .env
    networks:
      - mysqlnet
    depends_on:
      - mysqldb
    

  mysqldb:
    image: mysql
    env_file:
      - .sql.env
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    networks:
      - mysqlnet

volumes:
  mysql:
  mysql_config: